export type EarningsTiming = 'before_market' | 'during_market' | 'after_market';

// Raw API Ninjas transcript response — Developer tier fields only
export type NinjasTranscriptResponse = {
  ticker: string;
  cik: string;
  year: number;
  quarter: number;
  date: string;              // YYYY-MM-DD
  timestamp: string;         // full ISO timestamp if present
  earnings_timing: EarningsTiming;
  transcript: string;        // full text, typically 50K-60K chars

  // Fields present in the API response but LOCKED on Developer tier.
  // Kept as optional so the type is truthful, but we never rely on them:
  participants?: never;      // locked — extracted by Claude instead
  summary?: never;           // locked — generated by Claude instead
  guidance?: never;          // locked — generated by Claude instead
  risk_factors?: never;      // locked — generated by Claude instead
  overall_sentiment?: never; // locked — Claude computes multi-layer sentiment
  overall_sentiment_rationale?: never;
  transcript_split?: never;  // locked — Claude segments prepared vs Q&A
};

// Available quarters for a ticker (from /earningstranscriptsearch)
// year/quarter are coerced to number in the API wrapper — raw API returns strings
export type AvailableQuarter = {
  year: number;
  quarter: number;
};

// Formatted transcript for display
export type FormattedTranscript = {
  sections: Array<{
    type: 'prepared' | 'qa' | 'unknown';
    sentences: Array<{ id: string; text: string; speaker?: string }>;
  }>;
  total_sentences: number;
};

// Source attribution — attach to every rendered value
export type SourceLabel =
  | 'API Ninjas (transcript)'
  | 'API Ninjas (earnings)'
  | 'API Ninjas (calendar)'
  | 'Yahoo Finance'
  | 'Claude analysis';

export type Sourced<T> = {
  value: T;
  source: SourceLabel;
  as_of_date: string;
};

// --- Claude analysis types ---

export type ClaudeParticipant = {
  name: string;
  role: string;        // e.g., "Chief Executive Officer", "Analyst"
  company: string;     // issuer name for executives, firm name for analysts
  speaker_type: 'executive' | 'analyst' | 'operator' | 'unknown';
};

// Replaces what we lost from API Ninjas premium fields
export type ClaudeBaselineAnalysis = {
  executive_summary_paragraph: string;      // 3-4 sentence plain summary
  forward_guidance: Array<{
    metric: string;
    value: string;
    direction: 'raised' | 'lowered' | 'maintained' | 'initiated';
    source_sentence_id: string;
  }>;
  risk_factors: Array<{
    risk: string;
    severity: 'high' | 'medium' | 'low';
    source_sentence_id: string;
  }>;
  participants: ClaudeParticipant[];
};

// Structured REIT-specific summary
export type ClaudeSummary = {
  executive_summary: string[];
  key_themes: Array<{ title: string; rationale: string }>;
  key_risks: string[];
  notable_quotes: Array<{
    speaker: string;
    quote: string;
    sentence_id: string;
  }>;
};

export type ClaudeSentiment = {
  overall: { score: number; confidence: number };
  sections: { prepared: number; qa: number };
  topics: {
    demand: number;
    financing: number;
    rent_growth: number;
    development: number;
    guidance: number;
  };
  rationale: string;
};

export type ClaudeSignal = {
  sentence: string;
  sentence_id: string;
  category: 'Sector' | 'Geography' | 'Macro';
  tag: string;
  polarity: 'positive' | 'negative' | 'neutral';
  confidence: number;
  speaker: string;
};

export type ClaudeKPI = {
  metric:
    | 'FFO'
    | 'AFFO'
    | 'same_store_noi'
    | 'occupancy'
    | 'leasing_spread'
    | 'rent_growth'
    | 'cap_rate'
    | 'development_pipeline';
  value: string;
  context: string;
  source_sentence: string;
};

// Full Claude analysis output (everything Claude generates from a transcript)
export type ClaudeFullAnalysis = {
  baseline: ClaudeBaselineAnalysis;
  summary: ClaudeSummary;
  sentiment: ClaudeSentiment;
  signals: ClaudeSignal[];
  kpis: ClaudeKPI[];
};

// REIT universe
export type REIT = {
  ticker: string;
  company_name: string;
  sector: string;
  subsector: string | null;
  reit_type: 'Equity' | 'Mortgage';
  market_cap_musd: number;
};
